version: '3.9'

services:
  saApi:
    container_name: saApi
    image: ${DOCKER_REGISTRY-}saapi
    build:
      context: Backend/saApi
      dockerfile: Dockerfile

    environment:
      - ASPNETCORE_URLS=http://+:5300
      - ApiKey=6c7c427870msh77540ee5ce1cf0fp1589f8jsn9777cc8b6bb4

    ports:
      - "5300:5300"
      - "5301:5301"

    networks:
      - custom-network

    depends_on:
      db:
        condition: service_healthy
        
  dbApi:
    container_name: dbApi
    image: ${DOCKER_REGISTRY-}dbapi
    build:
      context: Backend/dbApi
      dockerfile: Dockerfile

    environment:
      - ASPNETCORE_URLS=http://+:5200
      - ConnectionString=server=db;port=3306;user=root;password=root;database=db

    ports:
      - "5200:5200"
      - "5201:5201"

    networks:
      - custom-network

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: Database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"

    networks:
      - custom-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8080:80
      
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
